[tool.poetry]
name = "data-model-module"
version = "0.1.10"
description = ""
authors = ["parkyoungjin-888 <pyj8813@gmail.com>"]
readme = "README.md"
exclude = ["model_file"]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.4"
boto3 = "^1.38.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
